config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("homepage.urls",namespace="homepage"))
]


if settings.DEBUG:
    urlpatterns = urlpatterns + \
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + \
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

homepage/urls.py
from django.urls import path
from .views import (index,about,contact,
news,
sifuBwana,
printing,
delivery,
sifuniBwana2,
get_a_quote,
sifuB,
otherHymn,
ExerciseBooks)

app_name = "homepage"

urlpatterns = [
    path("",index,name="index"),
    path("about/",about,name="about"),
    path("contact/",contact,name="contact"),
    path("news/",news,name="news"),
    path("sifuBwana/",sifuBwana,name="sifuBwana"),
    path("printing/",printing,name="printing"),
    path("delivery/",delivery,name="delivery"),
    path("get_a_quote/",get_a_quote,name="get_a_quote"),
    path("sifuniBwana2/",sifuniBwana2,name="sifuniBwana2"),
    path("sifuB/",sifuB,name="sifuB"),
    path("otherHymn/",otherHymn,name="otherHymn"),
    path("ExerciseBooks/",ExerciseBooks,name="ExerciseBooks")
  
]

homepage/models.py
from django.db import models
import os
import random

# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name,ext = os.path.splitext(base_name)
    return name, ext


def upload_image_path(instance,filename):
    new_filename = random.randint(1,999992345677653234)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename,ext = ext)
    return "image/{new_filename}/{final_filename}".format(new_filename=new_filename,final_filename = final_filename )



class BooksHolder(models.Model):
    book_title = models.CharField(max_length=255)
    book_link = models.URLField()
    book_image = models.FileField(upload_to=upload_image_path)

    def __str__(self) -> str:
        return self.book_title




class PaperSizes(models.Model):
    paper_size = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.paper_size


class Binding(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name


class PaperFortext(models.Model):
    name = models.CharField(max_length=255)


    def __str__(self) -> str:
        return self.name


class ColorFortext(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name

class PrintedSideOfPapertext(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name



class PaperCover(models.Model):
    name = models.CharField(max_length=255)


    def __str__(self) -> str:
        return self.name


class ColorForCover(models.Model):
    name = models.CharField(max_length=255)


    def __str__(self) -> str:
        return self.name


class PrintedSidesOfThePaperCover(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.name



class Banner(models.Model):
    subtitle = models.CharField(max_length=255)
    title = models.TextField()
    image = models.FileField(upload_to=upload_image_path)


    def __str__(self) -> str:
        return self.subtitle



class AboutTeam(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    


    def __str__(self) -> str:
        return self.name



class KijabeSerivices(models.Model):
    service_image =  models.FileField(upload_to=upload_image_path)
    service_name = models.CharField(max_length=255)

    def __str__(self) -> str:
        return self.service_name


class PlaystoreBook(models.Model):
    name  = models.CharField(max_length=255)
    price = models.CharField(max_length=255, blank=True,null=True)
    book_description = models.CharField(max_length=255,blank=True,null=True)
    sifuBwana = models.BooleanField(default=False)
    book_image = models.FileField(upload_to=upload_image_path,blank=True,null=True)

    url = models.URLField()


    def __str__(self) -> str:
        return self.name

homepage/views.py
from django.shortcuts import render
from .models import (BooksHolder,
PaperSizes,
Binding,
PaperFortext,
ColorFortext,
PrintedSideOfPapertext,
PaperCover,
ColorForCover,
PrintedSidesOfThePaperCover,
Banner,
AboutTeam,
KijabeSerivices,
PlaystoreBook)

# Create your views here.


def get_a_quote(request):

    context = {
         "home_nav":"",
        "nav_about":"",
        "nav_sifu_bwana":"",
        "nav_news":"",
        "nav_get_a_quote":"active",
        "nav_contact":"",
         "nav_printing":"",
       
    }

    return render(request,'get_a_quote.html',context)



def index(request):

    kijabe_services =  KijabeSerivices.objects.all()
    all_books = BooksHolder.objects.all()
    all_paper_size = PaperSizes.objects.all()
    all_bindings = Binding.objects.all()
    all_paper_for_text = PaperFortext.objects.all()
    all_color_for_text = ColorFortext.objects.all()
    printed_sides = PrintedSideOfPapertext.objects.all()
    paper_cover = PaperCover.objects.all()
    color_for_cover =  ColorForCover.objects.all()
    printed_sides_of_paper = PrintedSidesOfThePaperCover.objects.all()
    bb =  Banner.objects.all()

    context = {
        "all_books":all_books,
        "home_nav":"active",
        "nav_about":"",
        "nav_sifu_bwana":"",
        "nav_news":"",
        "nav_get_a_quote":"",
        "nav_contact":"",
         "nav_printing":"",
        "kijabe_services":kijabe_services,


        "paper_size":all_paper_size,
        "all_bindings":all_bindings,
        "all_paper_for_text":all_paper_for_text,
        "all_color_for_text":all_color_for_text,
        "printed_sides":printed_sides,
        "paper_cover":paper_cover,
        "color_for_cover":color_for_cover,
        "printed_sides_of_paper":printed_sides_of_paper,
        "banner":bb
    }
    return render(request,'index.html',context)


def about(request):

    team =  AboutTeam.objects.all()


    context = {
         "home_nav":"",
        "nav_about":"active",
        "nav_sifu_bwana":"",
        "nav_news":"",
        "nav_get_a_quote":"",
        "nav_contact":"",
         "nav_printing":"",
        "team":team
    }
    return render(request,'about.html',context)


def contact(request):
    context = {
         "home_nav":"",
        "nav_about":"",
        "nav_sifu_bwana":"",
        "nav_news":"",
         "nav_printing":"",
        "nav_get_a_quote":"",
        "nav_contact":"active",
    }
    return render(request,'contact.html',context)



def news(request):
    context = {
         "home_nav":"",
        "nav_about":"",
        "nav_sifu_bwana":"",
        "nav_news":"active",
        "nav_get_a_quote":"",
        "nav_contact":"",
         "nav_printing":"",
    }
    return render(request,'news.html',context)



def sifuBwana(request):
    all_s =  PlaystoreBook.objects.all()
    print(all_s)
    books = len(all_s)/2
    book1  = None
    book2 = None
    print(books)
    context = {
     "home_nav":"",
        "nav_about":"",
        "nav_sifu_bwana":"active",
        "nav_news":"",
        "nav_get_a_quote":"",
        "nav_contact":"",
        "nav_printing":"",
        "all_s":all_s
   }
    return render(request,'sifuniBBooks.html',context)



def printing(request):
    context = {
     "home_nav":"",
        "nav_about":"",
        "nav_sifu_bwana":"",
        "nav_news":"",
        "nav_get_a_quote":"",
        "nav_contact":"",
        "nav_printing":"active",
        
   }

    return render(request,'printing.html',context)



def delivery(request):

    return render(request,'delivery.html')



def sifuniBwana2(request):
    all_s = PlaystoreBook.objects.filter(sifuBwana =  True)

    context = {
        "all_books" :all_s
    }

    return render(request,'sifuniBBooks.html',context)

def sifuB(request):
    return render(request,'sifuBwana1.html')


def otherHymn(request):
    all_s =  PlaystoreBook.objects.filter(sifuBwana =  False )

    context = {
        "all_s":all_s
    }
    return render(request,'otherHymn.html',context)


def ExerciseBooks(request):
    return render(request,'exercise_books.html')

homepage/templates/contact.html
{% extends 'base.html' %}

{% load static %}


{% block content %}



    <!-- Header Banner -->
    <div class="banner-header section-padding valign bg-img bg-fixed" data-overlay-dark="3" data-background="{% static 'assets/img/slider/19.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-left caption mt-90">
                    <h5>Get in touch</h5>
                    <h1>Contact Us</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Contact -->
    <section class="contact section-padding">
        <div class="container">
            <div class="row mb-90">
                <div class="col-md-6 mb-60">
                    <h3>HEAD OFFICE</h3>
                    <p> Our Head Office is located at AIC Kijabe Mission Station Off Nairobi- Naivasha Highway</p>
                    <div class="reservations mb-30">
                        <div class="icon"><span class="flaticon-call"></span></div>
                        <div class="text">
                            <p>Tel</p> <a href="tel:0715-672-029">0715 672 029</a>
                        </div>
                    </div>
                    <div class="reservations mb-30">
                        <div class="icon"><span class="flaticon-envelope"></span></div>
                        <div class="text">
                            <p>Email Info</p> <a href="mailto:administration@kijabeprintingpress.co.ke">administration@kijabeprintingpress.co.ke</a>
                            <p>Email Info</p> <a href="mailto:customercare@kijabeprintingpress.co.ke">customercare@kijabeprintingpress.co.ke</a>
                        </div>
                    </div>
                    <div class="reservations">
                        <div class="icon"><span class="flaticon-location-pin"></span></div>
                        <div class="text">
                            <p>Address</p> P.O. Box 40 -00220, KIJABE
                            <br>AIC Kijabe Printing Press,
                        </div>
                    </div>
                </div>
                <div class="col-md-5 mb-30 offset-md-1">
                    <h3>Get in touch</h3>
                    <form method="post" class="contact__form" action="mail.php">
                        <!-- form message -->
                        <div class="row">
                            <div class="col-12">
                                <div class="alert alert-success contact__msg" style="display: none" role="alert"> Your message was sent successfully. </div>
                            </div>
                        </div>
                        <!-- form elements -->
                        <div class="row">
                            <div class="col-md-6 form-group">
                                <input name="name" type="text" placeholder="Your Name *" required="">
                            </div>
                            <div class="col-md-6 form-group">
                                <input name="email" type="email" placeholder="Your Email *" required="">
                            </div>
                            <div class="col-md-6 form-group">
                                <input name="phone" type="text" placeholder="Your Number *" required="">
                            </div>
                            <div class="col-md-6 form-group">
                                <input name="subject" type="text" placeholder="Subject *" required="">
                            </div>
                            <div class="col-md-12 form-group">
                                <textarea name="message" id="message" cols="30" rows="4" placeholder="Message *" required=""></textarea>
                            </div>
                            <div class="col-md-12">
                                <button class="butn-dark"><a href="#0"><span>Send Message</span></a></button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
            <!-- Map Section -->
            <div class="row">
                <div class="col-md-12 map animate-box" data-animate-effect="fadeInUp">
                    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d510651.02304913616!2d36.334226307318616!3d-0.7643118836287894!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x3ec507e36e7f79d6!2sAlC%20Kijabe%20Printing%20Press!5e0!3m2!1sen!2ske!4v1670144542575!5m2!1sen!2ske" width="1200" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>   
                </div>
            </div>
        </div>
    </section>
 <!-- Contact -->
 <section class="contact section-padding">
    <div class="container">
        <div class="row mb-90">
            <div class="col-md-6 mb-60">
                <h3>MARKRTING OFFICE</h3>
                <p> Our MARKRTING OFFICE is located At A.I.C. Central Office, Upper Hill Road, Opposite Rahimtulla Towers</p>
                <div class="reservations mb-30">
                    <div class="icon"><span class="flaticon-call"></span></div>
                    <div class="text">
                        <p>Tel</p> <a href="tel:+254-202-184-852">+254 202 184 852</a>
                        <p>Tel</p> <a href="tel:+254-202-324-151">+254 702 324 151</a>
                    </div>
                </div>
                <div class="reservations mb-30">
                    <div class="icon"><span class="flaticon-envelope"></span></div>
                    <div class="text">
                        <p>Email Info</p> <a href="mailto:marketingmanager@kijabeprintingpress.co.ke">marketingmanager@kijabeprintingpress.co.ke</a>
                        <p>Email Info</p> <a href="mailto:sales@kijabeprintingpress.co.ke">sales@kijabeprintingpress.co.ke</a>
                    </div>
                </div>
                <div class="reservations">
                    <div class="icon"><span class="flaticon-location-pin"></span></div>
                    <div class="text">
                        <p>Address</p> P.O. Box 40 -00220, KIJABE
                        <br>AIC Kijabe Printing Press,
                    </div>
                </div>
            </div>
            <div class="col-md-5 mb-30 offset-md-1">
                <h3>Get in touch</h3>
                <form method="post" class="contact__form" action="mail.php">
                    <!-- form message -->
                    <div class="row">
                        <div class="col-12">
                            <div class="alert alert-success contact__msg" style="display: none" role="alert"> Your message was sent successfully. </div>
                        </div>
                    </div>
                    <!-- form elements -->
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input name="name" type="text" placeholder="Your Name *" required="">
                        </div>
                        <div class="col-md-6 form-group">
                            <input name="email" type="email" placeholder="Your Email *" required="">
                        </div>
                        <div class="col-md-6 form-group">
                            <input name="phone" type="text" placeholder="Your Number *" required="">
                        </div>
                        <div class="col-md-6 form-group">
                            <input name="subject" type="text" placeholder="Subject *" required="">
                        </div>
                        <div class="col-md-12 form-group">
                            <textarea name="message" id="message" cols="30" rows="4" placeholder="Message *" required=""></textarea>
                        </div>
                        <div class="col-md-12">
                            <button class="butn-dark"><a href="#0"><span>Send Message</span></a></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <!-- Map Section -->
        <div class="row">
            <div class="col-md-12 map animate-box" data-animate-effect="fadeInUp">
                <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d7977.596383774831!2d36.81581!3d-1.29568!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xe4f8c7ffe4151fe7!2sAIC%20Central%20Office!5e0!3m2!1sen!2ske!4v1670144980058!5m2!1sen!2ske" width="1200" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>   
            </div>
        </div>
    </div>
</section>



{% endblock content %}

homepage/templates/delivery.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


  <!-- Room Page Slider -->
  <header class="header slider">
    <div class="owl-carousel owl-theme">
        <!-- The opacity on the image is made with "data-overlay-dark="number". You can change it using the numbers 0-9. -->
        <div class="text-center item bg-img" data-overlay-dark="3" data-background="{% static 'assets/img/slider/11.webp' %}"></div>
        <div class="text-center item bg-img" data-overlay-dark="3" data-background="{% static 'assets/img/slider/17.jpg' %}"></div>
        <div class="text-center item bg-img" data-overlay-dark="3" data-background="{% static 'assets/img/slider/18.jpg' %}"></div>
    </div>
    <!-- arrow down -->
    <div class="arrow bounce text-center">
        <a href="#" data-scroll-nav="1" class=""> <i class="ti-arrow-down"></i> </a>
    </div>
</header>
<!-- Room Content -->
<section class="rooms-page section-padding" data-scroll-index="1">
    <div class="container">
        <!-- project content -->
        <div class="row">
            <div class="col-md-12"> 
                <span>
                    <i class="star-rating"></i>
                    <i class="star-rating"></i>
                    <i class="star-rating"></i>
                    <i class="star-rating"></i>
                    <i class="star-rating"></i>
                </span>
                <div class="section-subtitle">Our Services</div>
                <div class="section-title">Delivery Services</div>
            </div>
            <div class="col-md-8">
                <p class="mb-30">With our fleet of vehicles we do timely deliveries of your finished goods right at your doorstep. Delivery within Nairobi and its environs is at no extra charge.</p>
                <p class="mb-30">Tempus egestas sed sed risus pretium. Et sollicitudin ac orci phasellus egestas tellus rutrum tellus. Aliquam vestibulum morbi blandit cursus risus at. </p>
                <div class="row">
                    <div class="col-md-6">
                        <h6>We offer Delivery :-</h6>
                        <ul class="list-unstyled page-list mb-30">
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Books</p>
                                </div>
                            </li>
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Magazines</p>
                                </div>
                            </li>
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Diaries</p>
                                </div>
                            </li>
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Calendars</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-6">
                        
                        <ul class="list-unstyled page-list mb-30">
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Journals</p>
                                </div>
                            </li>
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Posters</p>
                                </div>
                            </li>
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Business Cards</p>
                                </div>
                            </li>
                            <li>
                                <div class="page-list-icon"> <span class="ti-check"></span> </div>
                                <div class="page-list-text">
                                    <p>Brochure</p>
                                </div>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-12">
                        <h6>Special Requests</h6>
                        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo eget magna fermentum iaculis eu non diam. </p>
                    </div>
                    
                    <div class="col-md-12">
                        <div class="butn-dark mt-15 mb-30"> <a href="contact.html"><span>Contact Us today for your Delivery</span></a> </div>
                    </div>
                </div>
            </div>
            
        </div>
    </div>
</section>


{% endblock content %}

homepage/templates/news.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

    <!-- Header Banner -->
    <div class="banner-header section-padding valign bg-img bg-fixed" data-overlay-dark="4" data-background="{% static 'assets/img/slider/1.jpg' %}">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-left caption mt-90">
                    <h5><a href="news.html">News</a> / Post Page</h5>
                    <h1>Welcome to kijabe News</h1>
                </div>
            </div>
        </div>
    </div>
    <!-- Post -->
    <section class="section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-8"> 
                    <img src="img/restaurant/19.jpg' %}" class="mb-30" alt="">
                    <h2>Our Mobile apps</h2>
                    <p>Quisque pretium fermentum quam, sit amet cursus ante sollicitudin vel. Morbi consequat risus consequat, porttitor orci sit amet, iaculis nisl. Integer quis sapien neceli ultrices euismod sit amet id lacus. Sed a imperdiet erat. Duis eu est dignissim lacus dictum hendrerit quis vitae mi. Fusce eu nulla ac nisi cursus tincidun. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer tristique sem eget leo faucibus porttitor.</p>
                    <p>Nulla vitae metus tincidunt, varius nunc quis, porta nulla. Pellentesque vel dui nec libero auctor pretium id sed arcu. Nunc consequat diam id nisl blani dinisim. Etiam commodo diam dolor, at scelerisque sem finibus sit amet. Curabitur id lectus eget purus finibus laoreet.</p>
                    <blockquote>
                        <p>Nulla facilisi. Sedeuter nunc vouta miss mollis sapien vel, conseyer tureution yer vintane in libero semper. Quisque ravida eros ut turpis interdum ornare. Inter miss they adama seder a imerdie fames ac ante ipsum primis in faucibus.</p> <cite>Micheal Martin</cite>
                    </blockquote>
                
                    <p>Design pretium fermentum quam, sit amet cursus ante sollicitudin vel. Morbi consequat risus consequat, porttitor orci sit amet, iaculis nisl. Integer quis sapien neceli ultrices euismod sit amet id lacus. Sed a imperdiet erat. Duis eu est dignissim lacus dictum hendrerit quis vitae mi. Fusce eu nulla ac nisi cursus tincidun. Interdum et malesuada fames ac ante ipsum primis in faucibus. Integer tristique sem eget leo faucibus porttitor.</p>
                    <div class="post-comment-section">
                        <div class="row">
                            <!-- Comment -->
                            <div class="col-md-12">
                                <div class="news-post-comment-wrap">
                                    <div class="post-user-comment"> <img src="{% static 'assets/img/team/8.png' %}" alt=""> </div>
                                    <div class="post-user-content">
                                        <span>
                                            <i class="star-rating"></i>
                                            <i class="star-rating"></i>
                                            <i class="star-rating"></i>
                                            <i class="star-rating"></i>
                                            <i class="star-rating"></i>
                                        </span>
                                        <h3>Robert Martin<span> 29 October 2022</span></h3>
                                        <p>Restaurant ultricies nibh non dolor maximus sceleue inte molliser rana neque nec tempor. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Sidebar -->
                <div class="col-md-4">
                    <div class="news2-sidebar row">
                        <div class="col-md-12">
                            <div class="widget search">
                                <form>
                                    <input type="text" name="search" placeholder="Type here ...">
                                    <button type="submit"><i class="ti-search" aria-hidden="true"></i></button>
                                </form>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="widget">
                                <div class="widget-title">
                                    <h6>Recent Posts</h6>
                                </div>
                                <ul class="recent">
                                    <li>
                                        <div class="thum"> <img src="{% static 'assets/img/restaurant/16.jpeg' %}" alt=""> </div> 
                                        <a href="post.html">Sifu Bwana</a>
                                    </li>
                                    <li>
                                        <div class="thum"> <img src="{% static 'assets/img/restaurant/17.jpeg' %}" alt=""> </div> 
                                        <a href="post.html">Our Mobile Apps</a>
                                    </li>
                                    <li>
                                        <div class="thum"> <img src="{% static 'assets/img/restaurant/18.jpg' %}" alt=""> </div> 
                                        <a href="post.html">New Books</a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="zxx">

{% include 'head.html' %}

<body>

{% include 'preloader.html' %}

{% comment %} <div class="progress-wrap cursor-pointer">
    <svg class="progress-circle svg-content" width="100%" height="100%" viewbox="-1 -1 102 102">
        <path d="M50,1 a49,49 0 0,1 0,98 a49,49 0 0,1 0,-98"></path>
    </svg>
</div> {% endcomment %}


{% include 'nav.html' %}


{% block content %}{% endblock content %}


{% include 'footer.html' %}


{% include 'js.html' %}

</body>
</html>

templates/footer.html
{% load static %}

<footer class="footer">
    <div class="footer-bottom">
           <div class="container">
               <div class="row">
                   <div class="col-md-12">
                       <div class="footer-bottom-inner">
                           <p class="footer-bottom-copy-right">© Copyright 2022 by <a href="#">Joselikimani@gmail.com</a></p>
                       </div>
                   </div>
               </div>
           </div>
       </div>
</footer>

templates/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg">
    <div class="">
        <!-- Logo -->
        <div class="logo-wrapper navbar-brand valign">
            <a href="index.html">
                <div class="logo">
                    <img src="{% static 'assets/img/logoo.png' %}" class="logo-img" alt="">
                </div>
            </a>
        </div>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> <span class="icon-bar"><i class="ti-line-double"></i></span> </button>
        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">

                    <a class="nav-link {{home_nav}}" id="home_nav" href="{% url 'homepage:index' %}">Home</a>
                </li>
                <li class="nav-item"><a class="nav-link {{nav_about}}" id='nav_about' href="{% url 'homepage:about' %}">About</a></li>
                <li class="nav-item"><a class="nav-link {{nav_printing}}" id='nav_about' href="{% url 'homepage:printing' %}">Printing Services</a></li>
                <li class="nav-item"><a class="nav-link {{nav_printing}}" id='nav_about' href="{% url 'homepage:sifuB' %}">Our Products</a></li>
                

                <li class="nav-item"><a class="nav-link {{nav_sifu_bwana}}" id="nav_sifu_bwana" href="{% url 'homepage:sifuBwana' %}">Sifu Bwana</a></li>
                <li class="nav-item"><a class="nav-link {{nav_news}}" id="nav_news" href="{% url 'homepage:ExerciseBooks' %}">Exercise Book</a></li>
                <li class="nav-item"><a class="nav-link {{nav_get_a_quote}}" id="nav_get_a_quote" href="{% url 'homepage:get_a_quote' %}">Bible Production</a></li>
                <li class="nav-item"><a class="nav-link {{nav_contact}}" id="nav_contact" href="{% url 'homepage:contact' %}">Contact</a></li>
            </ul>
        </div>
    </div>
</nav>